CREATE TABLE IF NOT EXISTS claim
(
    id varchar(100) NOT NULL,
    claim_type varchar(20) NOT NULL,
    pix_key varchar(100) NOT NULL,
    key_type varchar(20) NOT NULL,
    claimer_participant integer NOT NULL,
    claimer_branch varchar(4),
    claimer_account_number varchar(20) NOT NULL,
    claimer_account_type varchar(20) NOT NULL,
    claimer_account_opening_date timestamp NOT NULL,
    claimer_type varchar(20) NOT NULL,
    claimer_tax_id varchar(14) NOT NULL,
    claimer_name varchar(100),
    donor_participant integer,
    status varchar(30),
    completion_period_end timestamp ,
    resolution_period_end timestamp ,
    last_modified timestamp ,
    creation_date timestamp ,
    update_date timestamp ,
    cancel_reason varchar(20) NULL,
    confirm_reason varchar(20) NULL,
    cancelled_by_claimant varchar(20) NULL,
    correlation_id varchar(32) NULL,
    CONSTRAINT claim_pkey PRIMARY KEY (id)
);
