CREATE TABLE IF NOT EXISTS JOB_EXECUTION  (
	id serial NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL,
	END_TIME TIMESTAMP DEFAULT NULL,
	TYPE  VARCHAR(100),
	EXIT_MESSAGE VARCHAR(2500),
	CONSTRAINT job_execution_primary_key PRIMARY KEY (id)
);
