/*
 *  baas-pix-dict 1.0 17/03/21
 *  Copyright (c) 2021, PicPay S.A. All rights reserved.
 *  PicPay S.A. proprietary/confidential. Use is subject to license terms.
 */

package com.picpay.banking.pix.core.events;

public enum EventType {

    PIX_KEY_CREATE_PENDING,
    PIX_KEY_UPDATE_PENDING,
    PIX_KEY_REMOVE_PENDING,
    PIX_KEY_CREATED_BACEN,
    PIX_KEY_REMOVED_BACEN,
    PIX_KEY_UPDATED_BACEN,
    PIX_KEY_FAILED_BACEN,

    CLAIM_CREATE_PENDING,
    CLAIM_CANCEL_PENDING,
    CLAIM_CONFIRM_PENDING,
    CLAIM_COMPLETE_PENDING,
    CLAIM_CREATED_BACEN,
    CLAIM_CANCELED_BACEN,
    CLAIM_CONFIRMED_BACEN,
    CLAIM_COMPLETED_BACEN,
    CLAIM_FAILED_BACEN,

    INFRACTION_REPORT_CREATE_PENDING,
    INFRACTION_REPORT_ANALYZE_PENDING,
    INFRACTION_REPORT_CANCEL_PENDING,
    INFRACTION_REPORT_CREATED_BACEN,
    INFRACTION_REPORT_ANALYZING_BACEN,
    INFRACTION_REPORT_CANCELED_BACEN,
    INFRACTION_REPORT_FAILED_BACEN;

}
